<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>DotRun</PackageId>
    <Description>Simple task automation for .NET single-file scripts</Description>
    <Version>0.0.1</Version>
    <Authors>Ade Attwood</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
  </ItemGroup>

</Project>
